---
substitutions:
  device: iku-mqtt-client
  name: IKU MQTT Client
  reboot_timeout: 1h

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: ${reboot_timeout}
  ap:
    ssid: ${device}
    password: !secret ap_wifi_password
captive_portal:

web_server:
  auth:
    username: admin
    password: !secret web_password
  local: true

ota:

mqtt:
  broker: !secret mqtt_broker

logger:
  level: DEBUG

dallas:
  - pin: D7

button:
  - platform: restart
    name: ${name} Restart

binary_sensor:
  - platform: status
    name: ${name} Status

text_sensor:
  - platform: version
    name: ${name} ESPHome Version
  - platform: wifi_info
    ip_address:
      name: ${name} IP Address
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

sensor:
  - platform: wifi_signal
    name: ${name} WiFi Signal
  - platform: uptime
    name: ${name} Uptime
    unit_of_measurement: h
    filters:
      - lambda: return int((x + 1800.0) / 3600.0);
  - platform: dallas
    address: !secret dallas_id_1
    name: ${name} Temperature
